### ISSUE TITLE
I can't find the following function, Where needs to be set?

### ISSUE THREAD

**Issue by xiaohu036** [adamwulf/touch-chart#18]
https://getlooseleaf.com/all-vines/videos/1171219578219847680.mp4

**Comment by adamwulf** [comment]
The demo app that's shown in that video is available in the [Loose Leaf](https://github.com/adamwulf/loose-leaf) repo. Look for the Little Clipper launch target. It uses touch-chart, as well as [Clippent Bezier](https://github.com/adamwulf/ClippingBezier) library.

**Comment by xiaohu036** [comment]
First of all, thank you for answering me .
     [The effect I need just like this](https://github.com/xiaohu036/CLPhotoBrowser/blob/master/1.gif),  When you finish drawing ,you can fill the blank area . As you know, There are some problems .1、 I don't want to turn into a PNG format picture .2、There is a sawtooth on the side .
     I think if I can get the Bessel curve in the blank area, I can solve this problem.  The method you provide seems to be not good enough to get the Bessel curve in the blank area , can you help me to solve this problem? Thank you

**Comment by xiaohu036** [comment]
First of all, thank you for answering me .
 [The effect I need just like this](https://github.com/xiaohu036/CLPhotoBrowser/blob/master/1.gif),  when you finish drawing ,you can fill the blank area . As you know, there are some problems .1、 I don't want to turn into a PNG format picture .2、There is a sawtooth on the side .
 I think if I can get the bezier curve in the blank area, I can solve this problem.  But the method you provide seems to be not good enough to get the Bessel curve in the blank area , can you help me to solve this problem? Thank you

**Comment by adamwulf** [comment]
That's slightly trickier, and isn't handled by ClippingBezier out of the box. Right now the library handles clipping between two paths, but not for a self-intersecting path. To do that, I think you'd want to run the clipping method as you add each segment to the path. So you'd be able to ask for the intersection point between the existing path and the new path element. If no intersection point comes up, then continue as normal. If one does, then use intersection point all the way to the new path element as a new closed shape.

It's a tricky problem with no easy answers. It'll take some experimentation and a fair bit of custom bezier code to get want you want without rasterizing to a png.
